server:
  port: 8071

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway_service
  cloud:
    gateway:
      # https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/appendix.html
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: gatewayfirst        # route ID, unique
          uri: lb://TESTPROJECT   # sub service
          predicates:             # assertion
            - Path=/tp/**  #
          filters:
            - StripPrefix=1
        - id: frontendProject
          uri: lb://FRONTEND
          predicates:
            - Path=/fe/**
          filters:
            - StripPrefix=1
        - id: blogProject
          uri: lb://BLOGSERVICE
          predicates:
            - Path=/blog/**
          filters:
            - StripPrefix=1
        - id: dataProject
          uri: lb://DATASERVICE
          predicates:
            - Path=/db/**
          filters:
            - StripPrefix=1
